

    
 



import randomItem  from "random-item"
// Function to generate a recommendation based on user preferences
function recommendation(preferencesJsonString) {
    const preferencesObject = JSON.parse(preferencesJsonString);
    const preferences = preferencesObject.preferences;
    // Define an array of recommendations based on preferences
    const recommendations = {
        outdoor: [
            'Go for a hike in the nearest national park.',
    'Take a walk by the beach.',
    'Explore a nearby nature trail.',
    'Have a picnic in the park.',
    'Go camping in the wilderness.',
    'Visit a botanical garden.',
    'Try birdwatching in a nature reserve.',
    'Go kayaking or canoeing in a river.',
    'Join a guided nature walk.',
    'Go for a bike ride on a scenic trail.',
    'Try geocaching in your local area.',
    'Visit a nearby zoo or wildlife sanctuary.',
    'Go rock climbing at an outdoor climbing gym.',
    'Take a scenic drive through the countryside.',
    'Try horseback riding on a trail.',
    'Go fishing at a nearby lake or river.',
    'Explore a new city on foot.',
    'Try orienteering in a local park.',
    'Go on a photography expedition in nature.',
    'Visit a historical site or landmark.',
    'Go stargazing at a dark sky location.',
    'Try archery at an outdoor range.',
    'Go birdwatching at a bird sanctuary.',
    'Take a nature photography workshop.',
    'Explore a nearby cave system.',
    'Go on a wildlife safari tour.',
    'Try paddleboarding on a calm lake.',
    'Visit a vineyard and go wine tasting.',
    'Go on a hot air balloon ride over the countryside.',
    'Try mountain biking on a rugged trail.',
    'Join a local outdoor fitness class.',
    'Visit a nearby farm and pick your own produce.',
    'Go for a sunrise or sunset hike.',
    'Take a photography tour of a scenic area.',
    'Go on a horse-drawn carriage ride.',
    'Try slacklining in a park.',
    'Go on a whale-watching boat tour.',
    'Visit a nearby arboretum or botanical garden.',
    'Try bouldering at a local climbing spot.',
    'Go on a nature scavenger hunt.',
    'Visit a butterfly conservatory.',
    'Try horseback archery at a ranch.',
    'Go on a guided kayaking tour.',
    'Take a nature painting or sketching class.',
    'Go on a mushroom foraging expedition.',
    'Try horseback riding on the beach.',
    'Visit a nearby alpaca farm.',
    'Go on a birdwatching boat tour.',
    'Take a guided nature photography tour.',
    'Try stand-up paddleboarding on a river.',
    'Go on a nighttime wildlife tour.',
    'Visit a nearby botanical garden during a special event.',
    'Try horseback riding in a national park.',
    'Go on a tree canopy tour.',
    'Take a guided fishing trip.',
    'Try mountain climbing with a certified guide.',
    'Go on a llama trekking adventure.',
    'Visit a nearby wildlife rehabilitation center.',
    'Try ziplining through a forest canopy.',
    'Go on a guided nature drawing workshop.',
    'Visit a nearby lavender farm.',
    'Take a guided mushroom identification walk.',
    'Go on a nature photography expedition.',
    'Visit a nearby national wildlife refuge.',
    'Try horseback riding through a vineyard.',
    'Go on a guided wildlife tracking hike.',
    'Visit a nearby cider mill and orchard.',
    'Try kite flying on a windy day.',
    'Go on a guided butterfly watching tour.',
    'Take a guided wildlife photography tour.',
    'Go on a guided birding tour.',
    'Visit a nearby wildlife rehabilitation sanctuary.',
    'Try horseback riding through a forest trail.',
    'Go on a guided night hike to spot nocturnal animals.',
    'Visit a nearby bird of prey center.',
    'Try horseback riding along a river trail.',
    'Go on a guided botanical garden tour.',
    'Visit a nearby wildlife education center.',
    'Try horseback riding through a desert landscape.',
    'Go on a guided tidepooling excursion.',
    'Visit a nearby wildlife observation tower.',
    'Try horseback riding through a mountain trail.',
    'Go on a guided cave exploration tour.',
    'Visit a nearby wildflower garden.',
    'Try horseback riding through a meadow.',
    'Go on a guided bat watching tour.',
    'Visit a nearby nature education center.',
    'Try horseback riding through a canyon trail.',
    'Go on a guided estuary exploration tour.',
    'Visit a nearby wildlife observation blind.',
    'Try horseback riding through a wetland trail.',
    'Go on a guided nature soundscape walk.',
    'Visit a nearby bird ringing station.',
    'Try horseback riding through a prairie trail.',
    'Go on a guided insect identification walk.',
    'Visit a nearby wildlife rehabilitation hospital.',
    'Try horseback riding through a river trail.',
    'Go on a guided marine wildlife tour.',
    'Visit a nearby bird sanctuary during migration season.',
    'Try horseback riding through a coastal trail.',
    'Go on a guided plant identification walk.',
    'Visit a nearby butterfly garden.',
    'Try horseback riding through a woodland trail.',
    'Go on a guided wetland exploration tour.',
    'Visit a nearby wildlife photography hide.',
    'Try horseback riding through a countryside trail.',
    'Go on a guided wild bird watching tour.',
    'Visit a nearby reptile and amphibian center.',
    'Try horseback riding through a lakeside trail.',
    'Go on a guided forest ecology walk.',
    'Visit a nearby wildlife observation blind.',
    'Try horseback riding through a wetland trail.',
    'Go on a guided nature soundscape walk.',
    'Visit a nearby bird ringing station.',
    'Try horseback riding through a prairie trail.',
    'Go on a guided insect identification walk.',
    'Visit a nearby wildlife rehabilitation hospital.',
    'Try horseback riding through a river trail.',
    'Go on a guided marine wildlife tour.',
    'Visit a nearby bird sanctuary during migration season.',
    'Try horseback riding through a coastal trail.',
    'Go on a guided plant identification walk.',
    'Visit a nearby butterfly garden.',
    'Try horseback riding through a woodland trail.',
    'Go on a guided wetland exploration tour.',
    'Visit a nearby wildlife photography hide.',
    'Try horseback riding through a countryside trail.',
    'Go on a guided wild bird watching tour.',
    'Visit a nearby reptile and amphibian center.',
    'Try horseback riding through a lakeside trail.',
    'Go on a guided forest ecology walk.',
    'Visit a nearby wildlife observation blind.',
    'Try horseback riding through a wetland trail.',
    'Go on a guided nature soundscape walk.',
    'Visit a nearby bird ringing station.',
    'Try horseback riding through a prairie trail.',
    'Go on a guided insect identification walk.',
    'Visit a nearby wildlife rehabilitation hospital.',
    'Try horseback riding through a river trail.',
    'Go on a guided marine wildlife tour.',
    'Visit a nearby bird sanctuary during migration season.',
    'Try horseback riding through a coastal trail.',
    'Go on a guided plant identification walk.',
    'Visit a nearby butterfly garden.',
    'Try horseback riding through a woodland trail.',
    'Go on a guided wetland exploration tour.',
    'Visit a nearby wildlife photograph',
            
        ],
        indoor: [
            'Watch a movie at home.',
    'Read a book by the fireplace.',
    'Try out a new recipe in the kitchen.',
    'Start a DIY craft project.',
    'Have a board game night with friends or family.',
    'Do a home workout or yoga session.',
    'Listen to a podcast or audiobook.',
    'Experiment with indoor gardening or plant care.',
    'Do a puzzle or Sudoku challenge.',
    'Have a virtual Netflix party with friends.',
    'Learn a new instrument or practice playing one.',
    'Try your hand at painting or drawing.',
    'Write in a journal or start a blog.',
    'Have a karaoke night at home.',
    'Learn a new language with online resources.',
    'Do some DIY home improvement projects.',
    'Watch educational videos or documentaries.',
    'Try your hand at calligraphy or hand lettering.',
    'Explore virtual museum tours or art galleries.',
    'Have a themed dinner night at home.',
    'Play video games or online multiplayer games.',
    'Learn coding or programming languages online.',
    'Take online courses or workshops on various subjects.',
    'Do a home spa day with facials and massages.',
    'Organize and declutter your living space.',
    'Try meditation or mindfulness exercises.',
    'Experiment with cooking or baking new recipes.',
    'Do a virtual workout class or yoga session.',
    'Listen to music and dance around your living room.',
    'Create a vision board or set goals for the future.',
    'Have a movie marathon with your favorite films.',
    'Practice mindfulness or deep breathing techniques.',
    'Write letters to friends or family members.',
    'Try indoor photography or photo editing.',
    'Read inspiring quotes or poetry.',
    'Do a home science experiment or DIY project.',
    'Plan and organize your upcoming week or month.',
    'Try your hand at indoor gardening or terrarium making.',
    'Do a digital detox and spend time offline.',
    'Experiment with mixology and create new cocktails.',
    'Watch TED talks or inspirational speeches online.',
    'Try indoor rock climbing at a local gym.',
    'Attend virtual concerts or live performances online.',
    'Learn about art history or famous artists.',
    'Host a virtual book club with friends.',
    'Practice mindfulness coloring or drawing.',
    'Do a home theater night with popcorn and snacks.',
    'Try your hand at indoor archery or shooting range.',
    'Take online quizzes or trivia challenges.',
    'Learn about astronomy and stargaze indoors.',
    'Experiment with indoor hydroponic gardening.',
    'Explore virtual tours of famous landmarks or cities.',
    'Try indoor mini-golf or bowling.',
    'Host a virtual game night with friends.',
    'Learn about different cultures through cooking.',
    'Attend virtual workshops or webinars on interesting topics.',
    'Try indoor skydiving or trampoline parks.',
    'Listen to educational podcasts or audiobooks.',
    'Host a DIY home decor or craft night with friends.',
    'Experiment with indoor photography or portrait sessions.',
    'Learn about history through documentaries or books.',
    'Try indoor surfing or paddleboarding.',
    'Attend virtual cooking classes or baking workshops.',
    'Watch live streams of wildlife or nature cams.',
    'Experiment with indoor kite flying.',
    'Take online dance classes or learn a new dance style.',
    'Do a puzzle-solving challenge with friends or family.',
    'Try indoor ice skating or rollerblading.',
    'Host a virtual painting or drawing party.',
    'Learn about psychology or human behavior.',
    'Experiment with indoor balloon twisting or sculpting.',
    'Attend virtual wine tasting events or workshops.',
    'Practice mindfulness meditation or relaxation techniques.',
    'Try indoor laser tag or paintball.',
    'Learn about sustainable living practices and try them out.',
    'Experiment with indoor gardening or bonsai trees.',
    'Watch live streams of aquariums or marine life.',
    'Attend virtual meditation or yoga retreats.',
    'Host a virtual talent show or open mic night.',
    'Learn about philosophy or ethics.',
    'Try indoor go-kart racing or bumper cars.',
    'Experiment with indoor drone flying or racing.',
    'Watch live streams of cooking demonstrations or chefs.',
    'Attend virtual art classes or drawing workshops.',
    'Learn about different cultures through documentaries.',
    'Try indoor mini-golf or putt-putt courses.',
    'Host a virtual movie trivia night with friends.',
    'Learn about mythology or folklore from different cultures.',
    'Experiment with indoor watercolor painting or sketching.',
    'Attend virtual music concerts or live performances.',
    'Try indoor bubble soccer or bubble ball.',
    'Watch live streams of wildlife or nature documentaries.',
    'Attend virtual theater productions or performances.',
    'Learn about architecture or interior design.',
    'Experiment with indoor origami or paper crafts.',
    'Try indoor obstacle courses or ninja warrior training.',
    'Host a virtual karaoke competition with friends.',
    'Learn about different musical genres and artists.',
    'Experiment with indoor magic tricks or illusions.',
    'Try indoor gardening with succulents or cacti.',
    'Watch live streams of cooking competitions or challenges.',
            // Add more indoor recommendations...
        ],
        relaxing: [
            'Take a bubble bath with scented candles.',
            'Practice yoga or meditation.',
            'Listen to calming music and unwind.',
            'Enjoy a cup of herbal tea in bed.',
            'Indulge in a spa day at home.',
            'Do a mindfulness or deep breathing exercise.',
            'Watch a sunset or sunrise.',
            'Write in a journal or do some creative writing.',
            'Try aromatherapy with essential oils.',
            'Do some gentle stretching exercises.',
            'Take a leisurely nature walk in a park.',
            'Read a book in a cozy nook.',
            'Listen to the sounds of nature or a calming playlist.',
            'Take a nap in a hammock or under a tree.',
            'Practice tai chi or qigong.',
            'Watch a calming ASMR video.',
            'Try progressive muscle relaxation.',
            'Do a guided meditation or visualization exercise.',
            'Practice gratitude journaling.',
            'Watch the clouds go by and daydream.',
            'Do a digital detox and disconnect from screens.',
            'Sit by a fireplace and relax.',
            'Do a body scan meditation to relax each muscle.',
            'Watch the rain fall and listen to its soothing sound.',
            'Create a cozy reading corner with blankets and pillows.',
            'Try forest bathing or shinrin-yoku.',
            'Enjoy a cup of hot cocoa or warm cider.',
            'Do a gentle yoga flow for relaxation.',
            'Practice deep breathing exercises.',
            'Savor a piece of dark chocolate or your favorite treat.',
            'Listen to a guided sleep meditation.',
            'Try a progressive relaxation technique.',
            'Engage in a creative hobby like painting or crafting.',
            'Create a calming bedtime routine.',
            'Try a mindfulness walking meditation.',
            'Watch a calming fireplace video.',
            'Do a body relaxation exercise from head to toe.',
            'Practice mindfulness while drinking a cup of tea.',
            'Listen to a calming podcast or audiobook.',
            'Create a soothing atmosphere with candles and soft lighting.',
            'Try a loving-kindness meditation.',
            'Do a gentle restorative yoga practice.',
            'Spend time in a quiet garden or nature sanctuary.',
            'Listen to calming sounds like rain or ocean waves.',
            'Practice self-massage or use a massage tool.',
            'Try a warm bath with Epsom salts.',
            'Watch a relaxing nature documentary.',
            'Do a gentle stretching routine before bed.',
            'Engage in a creative writing exercise.',
            'Try a relaxation visualization exercise.',
            'Listen to a guided relaxation script.',
            'Do a gentle bedtime yoga sequence.',
            'Create a calming bedtime ritual with soothing music.',
            'Write down your worries in a journal to clear your mind.',
            'Try a warm cup of chamomile tea before bed.',
            'Listen to a guided body scan meditation.',
            'Practice progressive muscle relaxation in bed.',
            'Do a gentle stretching routine in the morning.',
            'Spend time in nature and connect with the earth.',
            'Practice deep belly breathing to relax.',
            'Watch a calming nature video on YouTube.',
            'Do a grounding meditation to feel centered.',
            'Try a gentle evening stroll in your neighborhood.',
            'Listen to a calming playlist of instrumental music.',
            'Write down things you are grateful for in a gratitude journal.',
            'Do a guided imagery meditation.',
            'Engage in a slow, mindful eating practice.',
            'Try a candlelight meditation for relaxation.',
            'Create a cozy space with blankets and pillows for relaxation.',
            'Listen to a calming bedtime story or guided meditation.',
            'Do a gentle yoga flow to unwind.',
            'Practice mindfulness while doing everyday activities.',
            'Engage in a loving-kindness meditation for yourself and others.',
            'Try a progressive muscle relaxation exercise in bed.',
            'Listen to a calming white noise machine or app.',
            'Do a gentle evening yoga practice to relax.',
            'Create a calming bedtime routine with soft lighting and music.',
            'Practice deep breathing exercises to calm the mind and body.',
            'Try a gentle meditation to ease into sleep.',
            'Listen to a guided meditation for sleep and relaxation.',
            'Do a gentle yoga sequence to release tension.',
            'Engage in a deep relaxation exercise before bed.',
            'Try a warm cup of herbal tea to relax.',
            'Create a calming bedtime environment with soothing scents.',
            'Listen to a calming rain soundscape or nature sounds.',
            'Do a gentle stretch before bed to relax muscles.',
            'Practice mindfulness meditation to quiet the mind.',
            'Try a bedtime meditation to promote relaxation and sleep.',
            'Engage in a progressive muscle relaxation exercise.',
            'Listen to a guided sleep meditation to unwind.',
            'Do a gentle yoga practice to relax and de-stress.',
            'Create a calming bedtime ritual to prepare for sleep.',
            'Practice deep breathing techniques for relaxation.',
            'Try a mindfulness meditation to calm the mind and body.',
            'Listen to a calming meditation app or podcast before bed.',
            'Engage in a body scan meditation to release tension.',
            'Do a relaxation visualization exercise to unwind.',
            'Create a peaceful environment with soft lighting and soothing music.',
            'Practice mindfulness while taking a warm bath or shower.',
            'Try a guided relaxation meditation to ease into sleep.',
            // Add more relaxing recommendations...
        ],
        adventure: [
           
                'Try indoor rock climbing at a local gym.',
                'Go zip-lining at an adventure park.',
                'Book a skydiving session for an adrenaline rush.',
                'Take a hot air balloon ride for a unique experience.',
                'Go on a bungee jumping adventure.',
                'Explore a cave or cavern system.',
                'Go scuba diving or snorkeling in the ocean.',
                'Try paragliding or hang gliding.',
                'Experience whitewater rafting or kayaking.',
                'Go on a jungle trekking adventure.',
                'Explore an abandoned building or ghost town.',
                'Try canyoning or canyoneering.',
                'Go on a helicopter tour of the city or countryside.',
                'Take a ride in a dune buggy or ATV.',
                'Try sandboarding or dune sledding.',
                'Go on a spelunking expedition in a cave.',
                'Explore a volcanic landscape or lava tube.',
                'Try ice climbing or glacier trekking.',
                'Go on a deep-sea fishing charter.',
                'Experience a high-speed jet boat ride.',
                'Try snowmobiling or snowshoeing in the winter.',
                'Go on a wildlife safari adventure.',
                'Explore a desert oasis or sand dunes.',
                'Try hang gliding or paragliding off a cliff.',
                'Go on a guided survival skills course.',
                'Experience a dog sledding adventure in the snow.',
                'Try mountain boarding or downhill skateboarding.',
                'Go on a guided caving expedition.',
                'Experience a whitewater kayaking adventure.',
                'Try zorbing or globe riding down a hill.',
                'Go on a guided canyoneering trip.',
                'Experience a wildlife photography expedition.',
                'Try kiteboarding or kite surfing on the water.',
                'Go on a guided mountain biking tour.',
                'Experience a flyboarding or jetpacking adventure.',
                'Try ice fishing or ice climbing in the winter.',
                'Go on a guided snowshoeing tour.',
                'Experience a polar bear viewing expedition.',
                'Try sand dune racing or off-road driving.',
                'Go on a guided mountain climbing expedition.',
                'Experience a helicopter skiing or snowboarding trip.',
                'Try ice diving or ice snorkeling in frozen lakes.',
                'Go on a guided whale watching tour.',
                'Experience a hot air ballooning adventure at sunrise.',
                'Try skydiving or BASE jumping off a cliff.',
                'Go on a guided rock climbing trip.',
                'Experience a night safari adventure.',
                'Try parasailing or parascending over the ocean.',
                'Go on a guided ice climbing expedition.',
                'Experience a wilderness survival challenge.',
                'Try kite landboarding or kite skiing on land.',
                'Go on a guided river rafting expedition.',
                'Experience a shark cage diving adventure.',
                'Try cliff jumping or canyon swinging.',
                'Go on a guided trekking adventure in the mountains.',
                'Experience a zip-lining adventure through the jungle.',
                'Try sea kayaking or ocean canoeing.',
                'Go on a guided mountaineering expedition.',
                'Experience a glacier hiking or ice trekking adventure.',
                'Try wakeboarding or wakesurfing on the water.',
                'Go on a guided off-road ATV tour.',
                'Experience a sand dune bashing or desert safari.',
                'Try whitewater canoeing or kayaking.',
                'Go on a guided snowboarding tour.',
                'Experience a fly fishing adventure in a remote river.',
                'Try skydiving or paragliding over a scenic landscape.',
                'Go on a guided rock climbing course.',
                'Experience a wildlife tracking adventure.',
                'Try deep-sea fishing or big game fishing.',
                'Go on a guided snowmobiling tour.',
                'Experience a camel trekking adventure in the desert.',
                'Try cave diving or cavern diving in underwater caves.',
                'Go on a guided backcountry skiing or snowboarding tour.',
                'Experience a horseback riding adventure in the wilderness.',
                'Try kite skiing or snow kiting on frozen lakes.',
                'Go on a guided glacier climbing expedition.',
                'Experience a canopy zipline tour through the rainforest.',
                'Try cliff diving or waterfall rappelling.',
                'Go on a guided hot air ballooning tour.',
                'Experience a wildlife canoeing or kayaking adventure.',
                'Try spearfishing or underwater hunting.',
                'Go on a guided volcano hiking expedition.',
                'Experience a heli-skiing or heli-boarding adventure.',
                'Try flyboarding or hoverboarding on the water.',
                'Go on a guided bobsledding or luge adventure.',
                'Experience a wildlife boat safari adventure.',
                'Try glacier kayaking or iceberg kayaking.',
                'Go on a guided sandboarding or sand skiing tour.',
                'Experience a whitewater stand-up paddleboarding adventure.',
                'Try parasailing or paragliding over a glacier.',
                'Go on a guided mountain unicycling or mountain biking tour.',
                'Experience a jet ski safari adventure.',
                'Try ice climbing or glacier hiking in the Arctic.',
                'Go on a guided canyon kayaking or river tubing tour.',
                'Experience a night skydiving or skydiving under the stars.',
                'Try snowkiting or snowskating in the mountains.',
                'Go on a guided via ferrata or iron road adventure.',
                'Experience a river surfing or river boogie boarding adventure.',
                'Try sand dune skiing or sand dune snowboarding.',
                'Go on a guided stand-up paddleboarding expedition.',
                'Experience a hydrospeeding or riverboarding adventure.',
                'Try ice canoeing or ice dragon boat racing on frozen rivers.',
                'Go on a guided cliff camping or cliff hammocking adventure.',
            // Add more adventure recommendations...
        ]
    };

    // Retrieve recommendations based on the first preference
    const firstPreference = preferences[0];
    const recommendationOptions = recommendations[firstPreference];

    // Generate a random recommendation from the available options
    const recommendation = randomItem(recommendationOptions);

    return recommendation;
}

export default recommendation









